import React, { useState } from 'react';
import { GeminiService } from '../../services/geminiService';
import { School } from '../../types';
import { FileText, Loader2, Download, CheckCircle } from 'lucide-react';

interface StateReportingProps {
  school: School;
}

export const StateReporting: React.FC<StateReportingProps> = ({ school }) => {
  const [report, setReport] = useState('');
  const [loading, setLoading] = useState(false);
  
  const handleGenerate = async () => {
    setLoading(true);
    // Mock compliance data that would usually be calculated from DB
    const complianceData = {
      totalStudents: school.totalStudents,
      immunizationRate: school.complianceRate,
      missingRecords: Math.round(school.totalStudents * (1 - school.complianceRate / 100)),
      communicableOutbreaks: 0,
      screeningsCompleted: {
        vision: '95%',
        hearing: '92%',
        scoliosis: '88%'
      },
      reportingPeriod: 'Fall 2024'
    };
    
    const text = await GeminiService.generateStateReport(school.name, complianceData);
    setReport(text);
    setLoading(false);
  };

  return (
    <div className="animate-fade-in max-w-4xl mx-auto space-y-6">
       <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
         <div>
            <h2 className="text-2xl font-bold text-slate-800">State Reporting Automation</h2>
            <p className="text-slate-500">Generate compliance narratives for the Department of Health.</p>
         </div>
         <button 
           onClick={handleGenerate}
           disabled={loading}
           className="bg-primary-600 hover:bg-primary-700 text-white px-5 py-2.5 rounded-lg font-medium shadow-sm flex items-center disabled:opacity-70 transition-all"
         >
           {loading ? <Loader2 className="animate-spin mr-2" /> : <FileText className="mr-2" />}
           {loading ? 'Generating Report...' : 'Generate Compliance Narrative'}
         </button>
       </div>

       {report && (
         <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="bg-slate-50 p-4 border-b border-slate-100 flex justify-between items-center">
               <div className="flex items-center text-slate-700 font-semibold">
                 <CheckCircle size={18} className="text-emerald-500 mr-2" />
                 Report Generated Successfully
               </div>
               <button className="text-slate-500 hover:text-primary-600 text-sm font-medium flex items-center">
                 <Download size={16} className="mr-1" /> Download PDF
               </button>
            </div>
            <div className="p-8">
              <textarea 
                readOnly
                className="w-full h-96 p-4 bg-slate-50 border border-slate-200 rounded-lg text-slate-700 font-serif leading-relaxed focus:outline-none resize-none"
                value={report}
              />
            </div>
            <div className="p-4 bg-slate-50 border-t border-slate-100 text-center text-xs text-slate-400">
               * This report is generated by AI based on current system data. Please review before official submission.
            </div>
         </div>
       )}

       {!report && !loading && (
         <div className="border-2 border-dashed border-slate-200 rounded-xl p-12 text-center">
            <div className="w-16 h-16 bg-slate-50 rounded-full flex items-center justify-center mx-auto mb-4">
               <FileText className="text-slate-300" size={32} />
            </div>
            <h3 className="text-lg font-medium text-slate-600">No report generated</h3>
            <p className="text-slate-400 max-w-md mx-auto mt-2">
              Click the generate button to analyze current student data and create a formal submission document.
            </p>
         </div>
       )}
    </div>
  );
};